//*CID://+vbdkR~:                             update#=   21;       //~vbdkR~
//**********************************************************       //~vaf6I~
//vbdk:171125 GTK2 GtkFileSelection was dprecated,GtkFileChooser is available from v2.4//~vbdkI~
//vbdj:171125 (GTK2) menu label Ctrl+x dose not change by SetupDialog:Accel On/Off//~vbdjI~
//vbd2:171114 (Wxe)Add SelectAll menuitem (changed shortcut of Openwith A->W, SaveAs ->Control+Shift+A)//~vbd2I~
//vb7t:170128 (gxe)Gtk3 deprecated                                 //~vb7tI~
//var8:140127 gtk3 suppott                                         //~var8I~
//vaf6:120604 (XXE) fildialog(gtkfileselection) display previous selection directory//~vaf6I~
//**********************************************************       //~vaf6I~
/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_framewindow (void);
#ifndef OPTGTK3                                                    //~vaf6I~
  #if GTK_CHECK_VERSION(2,4,0)	//GtkFileChooser is available      //~vbdkI~
GtkWidget *create_fileselection (GtkWidget *Pparent,int Pactionid,int *Pprc);//+vbdkR~
  #else                                                            //~vbdkI~
GtkWidget* create_fileselection (void);
  #endif                                                           //~vbdkI~
GtkWidget* create_colorselectiondialog (void);
GtkWidget* create_fontselectiondialog (void);
#else                                                              //~vaf6M~
GtkWidget *create_fileselection (GtkWidget *Pparent,int Pactionid,int *Pprc);//~vaf6M~
GtkWidget* create_colorselectiondialog (GtkWidget *Pparent);       //~vaf6M~
GtkWidget* create_fontselectiondialog (GtkWidget *Pparent);        //~vaf6I~
#endif                                                             //~vaf6M~
GtkWidget* create_aboutdlg (void);
GtkWidget* create_optiondlg (void);
GtkWidget* create_printdlg (void);
#ifdef GBL_INTERFACE                                               //~vaf6I~
	extern char *Gfileselectiondir;                                //~vaf6I~
#else                                                              //~vaf6I~
	#define GBL_INTERFACE                                          //~vaf6I~
	char *Gfileselectiondir;                                       //~vaf6I~
#endif                                                             //~vaf6I~
#ifndef OPTGTK3                                                    //+@@@@I~//+@@@@I//~vaf6I~
#ifndef SSS                                                        //~vbdjI~
char *interface_getmenuitemlabel(int Pmenuid); //by ID_FILE_NEW etc//~vbdjI~
#endif                                                             //~vbdjI~
#else   //OPTGTK3                                                  //+@@@@I//~vaf6I~
#ifndef CCC                                                        //~vaf6I~
    void interface_create_menu(GtkWidget *Ppframe,GtkWidget *Pvvox);              //+@@@@R//~vaf6R~
#endif                                                             //~vaf6I~
#ifdef BBB                                                         //~vaf6I~
	void interface_create_menu(GApplication *Ppapp);               //~vaf6I~
#endif                                                             //~vaf6I~
	void interface_create_window(GApplication *Ppapp);             //~vaf6I~
	void interface_quit();                                         //~vaf6I~
#endif                                                             //+@@@@I//~vaf6I~
#if GTK_CHECK_VERSION(3,10,0)                                      //~vb7tR~
    #define GTK3_STOCK_NEW      "document-new"                     //~vb7tR~
    #define GTK3_STOCK_OPEN     "document-open"                    //~vb7tR~
    #define GTK3_STOCK_SAVE     "document-save"                    //~vb7tR~
    #define GTK3_STOCK_SAVE_AS  "document-save-as"                 //~vb7tR~
    #define GTK3_STOCK_PRINT    "document-print"                   //~vb7tR~
    #define GTK3_STOCK_CUT      "edit-cut"                         //~vb7tR~
    #define GTK3_STOCK_CLEAR    "edit-clear"                       //~vb7tR~
    #define GTK3_STOCK_COPY     "edit-copy"                        //~vb7tR~
    #define GTK3_STOCK_PASTE    "edit-paste"                       //~vb7tR~
    #define GTK3_STOCK_SELECT_ALL "gtk-select-all"                 //~vbd2I~
    #define GTK3_STOCK_HOME     "go-home"                          //~vb7tR~
    #define GTK3_STOCK_QUIT     "application-exit"                 //~vb7tR~
    #define GTK3_STOCK_HELP     "help-browser"                     //~vb7tR~
	#define UACC_CONTROL_MASK   "<control>"                        //~vb7tR~
	#define UACC_SHIFT_MASK     "<shift>"  //for C+S+A:SaveAs      //~vbd2I~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_NEW                                           //~vb7tR~
    	#undef GTK_STOCK_NEW                                       //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_NEW  GTK3_STOCK_NEW                          //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_OPEN                                          //~vb7tR~
    	#undef GTK_STOCK_OPEN                                      //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_OPEN GTK3_STOCK_OPEN                         //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_SAVE                                          //~vb7tR~
    	#undef GTK_STOCK_SAVE                                      //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_SAVE GTK3_STOCK_SAVE                         //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_SAVE_AS                                       //~vb7tR~
    	#undef GTK_STOCK_SAVE_AS                                   //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_SAVE_AS GTK3_STOCK_SAVE_AS                   //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_PRINT                                         //~vb7tR~
    	#undef GTK_STOCK_PRINT                                     //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_PRINT GTK3_STOCK_PRINT                       //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_CUT                                           //~vb7tR~
    	#undef GTK_STOCK_CUT                                       //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_CUT GTK3_STOCK_CUT                           //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_CLEAR                                         //~vb7tR~
    	#undef GTK_STOCK_CLEAR                                     //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_CLEAR GTK3_STOCK_CLEAR                       //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_COPY                                          //~vb7tR~
    	#undef GTK_STOCK_COPY                                      //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_COPY GTK3_STOCK_COPY                         //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_PASTE                                         //~vb7tR~
    	#undef GTK_STOCK_PASTE                                     //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_PASTE GTK3_STOCK_PASTE                       //~vb7tR~
    #ifdef GTK_STOCK_SELECT_ALL                                    //~vbd2I~
    	#undef GTK_STOCK_SELECT_ALL                                //~vbd2I~
    #endif                                                         //~vbd2I~
    #define GTK_STOCK_SELECT_ALL GTK3_STOCK_SELECT_ALL             //~vbd2I~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_HOME                                          //~vb7tR~
    	#undef GTK_STOCK_HOME                                      //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_HOME GTK3_STOCK_HOME                         //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_QUIT                                          //~vb7tR~
    	#undef GTK_STOCK_QUIT                                      //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_QUIT GTK3_STOCK_QUIT                         //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_HELP                                          //~vb7tR~
    	#undef GTK_STOCK_HELP                                      //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_HELP GTK3_STOCK_HELP                         //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_OPEN                                          //~vb7tR~
    	#undef GTK_STOCK_OPEN                                      //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_OPEN   "gtk-open"                            //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_CANCEL                                        //~vb7tR~
    	#undef GTK_STOCK_CANCEL                                    //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_CANCEL "gtk-cancel"                          //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_CLOSE                                         //~vb7tR~
    	#undef GTK_STOCK_CLOSE                                     //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_CLOSE  "gtk-close"                           //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_OK                                            //~vb7tR~
    	#undef GTK_STOCK_OK                                        //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_OK     "gtk-ok"                              //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_YES                                           //~vb7tR~
    	#undef GTK_STOCK_YES                                       //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_YES     "gtk-yes"                            //~vb7tR~
                                                                   //~vb7tR~
    #ifdef GTK_STOCK_NO                                            //~vb7tR~
    	#undef GTK_STOCK_NO                                        //~vb7tR~
    #endif                                                         //~vb7tR~
    #define GTK_STOCK_NO      "gtk-no"                             //~vb7tR~
                                                                   //~vb7tR~
#endif    //GTK3.1                                                 //~vb7tR~
