//*CID://+vas0R~:                             update#=   33;       //+vas0R~
//************************************************************     //~vam0I~
//vas0:140219 (gxe:bug)gtk_application_new(NULLappid) is supported from v3.6//+vas0I~
//var8:140127 gtk3 suppott                                         //~var8I~
//vam0:130911 for distro removed gnome-print,use GTKprint          //~vam0I~
//************************************************************     //~vam0I~
/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#ifndef OPTGTK3                                                    //~var8R~
#include <gnome.h>
#else                                                              //~var8R~
	#include <gtk/gtk.h>                                           //~var8R~
	#include <libintl.h>                                           //~var8R~
	#include <libgnome/libgnome.h>                                 //~var8R~
#endif                                                             //~var8R~
#ifndef NOPRINT                                                    //~vam0R~
	#ifdef GTKPRINT                                                //~vam0R~
	#else    //!GTKPRINT                                           //~vam0I~
#include <libgnomeprint/gnome-print.h>                             //~5720I~
#include <libgnomeprint/gnome-print-job.h>                         //~5720I~
	#endif   //!GTKPRINT                                           //~vam0I~
#endif                                                             //~vam0I~
#if GTK_CHECK_VERSION(3,6,0)                                       //+vas0I~
	#define GTKV3060                                               //+vas0I~
#endif                                                             //+vas0I~

#include "interface.h"
#include "support.h"
#include "gxe.h"                                                   //~5609I~

int
main (int argc, char *argv[])
{
#ifndef OPTGTK3                                                    //~var8R~
  GtkWidget *framewindow;                                          //~5603R~
#endif                                                             //~var8R~

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

#ifndef OPTGTK3                                                    //~var8R~
  gnome_program_init (PACKAGE, VERSION, LIBGNOMEUI_MODULE,
                      argc, argv,
                      GNOME_PARAM_APP_DATADIR, PACKAGE_DATA_DIR,
                      NULL);
#else                                                              //~var8R~
//#ifndef GTK3GTK3                                                 //~var8R~
  gnome_program_init (PACKAGE, VERSION, LIBGNOME_MODULE,           //~var8R~
                      argc, argv,                                  //~var8R~
                      GNOME_PARAM_APP_DATADIR, PACKAGE_DATA_DIR,   //~var8R~
                      NULL);                                       //~var8R~
//#else                                                            //~var8R~
//#endif  //GTK3GTK3                                               //~var8R~
#endif  //OPTGTK3                                                  //~var8R~

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
#ifndef OPTGTK3                                                    //~var8R~
  gxe_init(argc,argv);					//pass main window handle  //~5613R~
  framewindow = create_framewindow ();                             
  gtk_widget_show (framewindow);                                   //~5603R~
  gtk_main ();
  return 0;
#else                                                              //~var8R~
//#ifndef GTK3GTK3                                                 //~var8R~
//  gtk_init(&argc,&argv);                                         //~var8R~
//  framewindow = create_framewindow ();                           //~var8R~
//  gxe_init(argc,argv);                  //pass main window handle//~var8R~
//  gtk_widget_show (framewindow);                                 //~var8R~
//  gtk_main ();                                                   //~var8R~
//  return 0;                                                      //~var8R~
//#else                                                            //~var8R~
    {                                                              //~var8R~
#ifdef AAA                                                         //~var8R~
	Gxe *app;                                                      //~var8R~
	int status;                                                    //~var8R~
	app = gxe_new ();                                              //~var8R~
	status = g_application_run (G_APPLICATION (app), argc, argv);  //~var8R~
	g_object_unref (app);                                          //~var8R~
	return status;                                                 //~var8R~
#else     //from gtk-demo                                          //~var8R~
	GtkApplication *app;                                           //~var8R~
//    GSettings      *settings;                                    //~var8R~
//  GAction        *action;                                        //~var8R~
    GApplicationFlags appflags;                                    //~var8R~
    int rc;                                                        //~var8R~
    //**********************                                       //~var8R~
	gtk_init(NULL,NULL);                                           //~var8R~
//  gxe_register_stock_icons();                                    //~var8R~
    appflags=G_APPLICATION_FLAGS_NONE;//G_APPLICATION_HANDLE_COMMAND_LINE;//call//~var8R~
//#ifdef FFF                                                       //+vas0R~
#ifndef GTKV3060                                                   //+vas0I~
    app=gtk_application_new("xe.gxe",appflags);//must contain '.'  //~var8R~
#else                                                              //~var8R~
    app=gtk_application_new(NULL/*available after 3.6*/,appflags);//must contain '.'//+vas0R~
#endif                                                             //~var8R~
//    settings=g_settings_new("xe.gxe");//application settings     //~var8R~
//    action=g_settings_create_action(settings,"gxeactions");//named action//~var8R~
//    g_action_map_add_action(G_ACTION_MAP(app),action);           //~var8R~
    g_signal_connect(app,"startup",G_CALLBACK(gxe_startup),NULL/*data*/);//~var8R~
    g_signal_connect(app,"activate",G_CALLBACK(gxe_activate),NULL/*data*/);//~var8R~
	gxe_init(argc,argv);				//xe preinit               //~var8R~
	rc=g_application_run(G_APPLICATION (app),0/*argc*/,NULL/*argv*/);//~var8R~
	return rc;                                                     //~var8R~
#endif                                                             //~var8R~
    }                                                              //~var8R~
//#endif  //GTK3GTK3                                               //~var8R~
#endif	//OPTGTK3                                                  //~var8R~
}
